# Generated by Django 5.2.7 on 2025-11-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
