# Generated by Django 5.2.7 on 2025-11-12 12:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audience_manager', '0001_initial'),
        ('campaign_manager', '0002_alter_campaign_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='enable_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='enable_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='enable_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaignlog',
            name='message_provider_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sequencestep',
            name='delay_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sequencestep',
            name='delay_weeks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('promotional', 'Promotional'), ('renewal', 'Renewal'), ('welcome', 'Welcome')], max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('scheduled', 'Scheduled')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='campaignlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('replied', 'Replied'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='sequencestep',
            name='trigger_condition',
            field=models.CharField(choices=[('always', 'Always Send'), ('no_response', 'Send if no response'), ('no_action', 'Send if no action taken')], default='always', max_length=20),
        ),
        migrations.CreateModel(
            name='PendingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm_pending_tasks', to='campaign_manager.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm_pending_tasks', to='audience_manager.audiencecontact')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm_pending_tasks', to='campaign_manager.sequencestep')),
            ],
        ),
    ]
