# Generated by Django 4.2.7 on 2025-11-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmanager',
            name='email_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('scheduled', 'Scheduled')], default='pending', help_text='Status of the email', max_length=20),
        ),
        migrations.AddField(
            model_name='emailmanager',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if email sending failed', null=True),
        ),
        migrations.AddField(
            model_name='emailmanager',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when email was sent', null=True),
        ),
        migrations.AddIndex(
            model_name='emailmanager',
            index=models.Index(fields=['email_status'], name='email_manag_email_s_a3103b_idx'),
        ),
    ]
