# Generated by Django 4.2.23 on 2025-09-22 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_provider', '0005_remove_communication_provider_mapping'),
        ('campaigns', '0009_alter_campaign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='communication_provider',
            field=models.ForeignKey(blank=True, help_text='Communication provider for this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='email_provider.emailproviderconfig'),
        ),
        migrations.AlterField(
            model_name='campaignscheduleinterval',
            name='communication_provider',
            field=models.ForeignKey(blank=True, help_text='Communication provider for this interval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_schedules', to='email_provider.emailproviderconfig'),
        ),
    ]
