# Generated by Django 4.2.23 on 2025-09-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_alter_campaign_communication_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignscheduleinterval',
            name='communication_provider',
        ),
    ]
