# Generated by Django 4.2.23 on 2025-09-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_migrate_campaigns_to_email_provider'),
        ('campaigns', '0011_remove_campaignscheduleinterval_communication_provider'),
    ]

    operations = [
    ]
