# Generated by Django 4.2.23 on 2025-09-30 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_campaign_current_status'),
        ('campaigns', '0012_merge_20250922_0754'),
    ]

    operations = [
    ]
