# Generated by Django 4.2.23 on 2025-09-30 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_merge_20250930_0625'),
        ('campaigns', '0013_remove_campaign_current_status'),
    ]

    operations = [
    ]
