# Generated by Django 4.2.23 on 2025-09-30 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_campaignrecipient_provider_message_id'),
        ('campaigns', '0014_merge_20250930_0644'),
    ]

    operations = [
    ]
