# Generated by Django 4.2.23 on 2025-10-07 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_provider', '0006_add_provider_specific_fields'),
        ('campaigns', '0015_merge_20250930_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignscheduleinterval',
            name='communication_provider',
            field=models.ForeignKey(blank=True, help_text='Communication provider for this interval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_schedules', to='email_provider.emailproviderconfig'),
        ),
    ]
