# Generated by Django 4.2.7 on 2025-11-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0002_rename_hierarchy_m_parent__9ccd30_idx_hierarchy_m_parent__9206de_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchymanagement',
            name='unit_type',
            field=models.CharField(choices=[('department', 'Department'), ('region', 'Region'), ('north_region', 'North Region'), ('state', 'State'), ('branch', 'Branch'), ('team', 'Team')], db_index=True, default='department', max_length=30),
        ),
    ]
