# Generated by Django 4.2.7 on 2025-11-05 09:28

import django.core.validators
from django.db import migrations, models, connection


def remove_unique_constraint(apps, schema_editor):
    """Remove unique constraint from manager_id column if it exists"""
    db_alias = schema_editor.connection.alias
    from django.db import connections
    db_connection = connections[db_alias]
    
    with db_connection.cursor() as cursor:
        # Try to find and drop all unique constraints on manager_id
        cursor.execute("""
            SELECT tc.constraint_name
            FROM information_schema.table_constraints tc
            JOIN information_schema.constraint_column_usage ccu
                ON tc.constraint_name = ccu.constraint_name
                AND tc.table_schema = ccu.table_schema
            WHERE tc.table_name = 'hierarchy_management'
                AND tc.constraint_type = 'UNIQUE'
                AND ccu.column_name = 'manager_id'
                AND tc.table_schema = 'public';
        """)
        
        results = cursor.fetchall()
        for result in results:
            constraint_name = result[0]
            cursor.execute(f'ALTER TABLE hierarchy_management DROP CONSTRAINT IF EXISTS {constraint_name} CASCADE;')
        
        # Also try dropping index if it exists as a unique index
        cursor.execute("""
            SELECT indexname
            FROM pg_indexes
            WHERE tablename = 'hierarchy_management'
                AND indexdef LIKE '%manager_id%'
                AND indexdef LIKE '%UNIQUE%';
        """)
        
        index_results = cursor.fetchall()
        for result in index_results:
            index_name = result[0]
            cursor.execute(f'DROP INDEX IF EXISTS {index_name};')


def reverse_remove_unique_constraint(apps, schema_editor):
    """Reverse operation - add unique constraint back (if needed)"""
    # Note: We don't reverse this as it would break existing data
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0003_add_north_region_unit_type'),
    ]

    operations = [
        migrations.RunPython(
            remove_unique_constraint,
            reverse_code=reverse_remove_unique_constraint
        ),
        migrations.AlterField(
            model_name='hierarchymanagement',
            name='manager_id',
            field=models.CharField(db_index=True, help_text='Manager ID in format mgr-XXX (e.g., mgr-002). One manager can be assigned to multiple hierarchy units.', max_length=20, validators=[django.core.validators.RegexValidator('^mgr-\\d{3}$', 'Manager ID must be in format mgr-XXX')]),
        ),
    ]
