# Generated by Django 4.2.17 on 2025-12-31 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_code_alter_client_name_and_more'),
        ('dnc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dncregistry',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dncsettings',
            options={},
        ),
        migrations.AddField(
            model_name='dncregistry',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dnc_entries', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='dncoverridelog',
            name='override_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dncsettings',
            name='allow_overrides',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dncsettings',
            name='auto_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dncsettings',
            name='block_contacts',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dncsettings',
            name='enable_checking',
            field=models.BooleanField(default=True),
        ),
    ]
