# Generated by Django 4.2.17 on 2025-12-03 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0026_merge_20251126_1050'),
        ('renewals', '0029_merge_20251128_0718'),
    ]

    operations = [
    ]
