# Generated by Django 4.2.17 on 2025-12-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0029_merge_20251203_1646'),
        ('renewals', '0030_merge_20251203_0451'),
    ]

    operations = [
    ]
