# Generated by Django 4.2.17 on 2025-12-09 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0029_merge_20251203_1258'),
        ('renewals', '0030_merge_20251203_1749'),
        ('renewals', '0031_merge_20251203_1130'),
    ]

    operations = [
    ]
