# Generated by Django 4.2.17 on 2025-12-16 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0031_merge_20251210_1324'),
        ('renewals', '0031_merge_20251210_1341'),
        ('renewals', '0032_merge_20251209_0801'),
    ]

    operations = [
    ]
