# Generated by Django 4.2.17 on 2025-12-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0030_merge_20251203_2046'),
        ('renewals', '0032_merge_20251218_1110'),
        ('renewals', '0033_merge_20251216_0601'),
    ]

    operations = [
    ]
