# Generated by Django 4.2.17 on 2025-12-23 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0032_merge_20251217_1201'),
        ('renewals', '0033_merge_20251219_1311'),
        ('renewals', '0034_merge_20251219_0935'),
    ]

    operations = [
    ]
