# Generated by Django 4.2.17 on 2025-12-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0034_merge_20251223_1213'),
        ('renewals', '0035_merge_20251223_0532'),
    ]

    operations = [
    ]
