# Generated by Django 4.2.17 on 2025-12-29 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0032_merge_20251219_1110'),
        ('renewals', '0036_merge_20251223_0720'),
    ]

    operations = [
    ]
