# Generated by Django 5.2.7 on 2025-12-10 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_inbox', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailfolder',
            name='folder_type',
            field=models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('drafts', 'Drafts'), ('trash', 'Trash'), ('spam', 'Spam'), ('junk', 'Junk'), ('archive', 'Archive'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailinboxmessage',
            name='category',
            field=models.CharField(choices=[('complaint', 'Complaint'), ('feedback', 'Feedback'), ('refund', 'Refund'), ('appointment', 'Appointment'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=20),
        ),
        migrations.CreateModel(
            name='BulkEmailCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('subject_template', models.CharField(help_text='Base subject from template', max_length=500)),
                ('body_html_template', models.TextField(help_text='Base HTML from template')),
                ('custom_subject', models.CharField(blank=True, help_text="User's custom subject override", max_length=500, null=True)),
                ('additional_message', models.TextField(blank=True, help_text="User's additional note", null=True)),
                ('recipients_data', models.JSONField(default=list, help_text="List of dicts: [{'email': 'x', 'name': 'y', 'company': 'z'}]")),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_recipients', models.IntegerField(default=0)),
                ('successful_sends', models.IntegerField(default=0)),
                ('failed_sends', models.IntegerField(default=0)),
                ('opened_count', models.IntegerField(default=0)),
                ('clicked_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bulk_email_campaigns',
                'ordering': ['-created_at'],
            },
        ),
    ]
