# Generated by Django 5.2.7 on 2025-11-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_inbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailfolder',
            name='folder_type',
            field=models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('drafts', 'Drafts'), ('trash', 'Trash'), ('spam', 'Spam'), ('junk', 'Junk'), ('archive', 'Archive'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
    ]
