# Generated by Django 5.2.7 on 2025-12-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_inbox', '0002_alter_emailfolder_folder_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailinboxmessage',
            name='custom_id',
            field=models.CharField(blank=True, help_text='Auto-generated ID like EMAIL-0001', max_length=50, null=True, unique=True),
        ),
    ]
