# Generated by Django 5.2.7 on 2025-12-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_inbox', '0003_bulkemailcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkemailcampaign',
            name='additional_message',
            field=models.TextField(blank=True, help_text="User's additional note", null=True),
        ),
        migrations.AddField(
            model_name='bulkemailcampaign',
            name='custom_subject',
            field=models.CharField(blank=True, help_text="User's custom subject override", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bulkemailcampaign',
            name='body_html_template',
            field=models.TextField(help_text='Base HTML from template'),
        ),
        migrations.AlterField(
            model_name='bulkemailcampaign',
            name='subject_template',
            field=models.CharField(help_text='Base subject from template', max_length=500),
        ),
    ]
