# Generated by Django 5.2.7 on 2025-11-25 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_inbox', '0004_remove_emailinboxmessage_email_inbox_assigne_1569ac_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailfolder',
            name='customer_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('hni', 'HNI (High Net Worth)'), ('super_hni', 'Super HNI'), ('vip', 'VIP')], default='normal', help_text='Customer categorization for support tiers', max_length=20),
        ),
        migrations.AddField(
            model_name='emailfolder',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailfolder',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailfolder',
            name='escalated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailfolder',
            name='escalation_priority',
            field=models.CharField(blank=True, choices=[('high', 'High Priority'), ('urgent', 'Urgent Priority'), ('critical', 'Critical Priority')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='emailfolder',
            name='escalation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailfolder',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="e.g., 'Viewed', 'Escalated', 'Category Changed'", max_length=50)),
                ('details', models.TextField(blank=True, help_text="Extra info like 'Changed from Normal to VIP'", null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('email_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='email_inbox.emailinboxmessage')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
