# Generated by Django 5.2.7 on 2025-12-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_inbox', '0004_bulkemailcampaign_additional_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkemailcampaign',
            name='clicked_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkemailcampaign',
            name='opened_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailinboxmessage',
            name='category',
            field=models.CharField(choices=[('complaint', 'Complaint'), ('feedback', 'Feedback'), ('refund', 'Refund'), ('appointment', 'Appointment'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=20),
        ),
    ]
