# Generated by Django 5.2.7 on 2025-11-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessagetemplate',
            name='language',
            field=models.CharField(choices=[('en_US', 'English (US)'), ('en', 'English'), ('hi', 'Hindi'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('pt', 'Portuguese'), ('ar', 'Arabic'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean')], default='en', max_length=10),
        ),
    ]
