# Generated by Django 5.2.7 on 2025-11-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsprovider',
            name='daily_limit',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='smsprovider',
            name='monthly_limit',
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='smsprovider',
            name='rate_limit_per_minute',
            field=models.PositiveIntegerField(default=10, help_text='Max messages per minute'),
        ),
    ]
