# Generated by Django 5.2.7 on 2025-11-19 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_provider', '0002_smsprovider_daily_limit_smsprovider_monthly_limit_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='smsmessage',
            table='sms_message',
        ),
        migrations.AlterModelTable(
            name='smsprovider',
            table='sms_provider',
        ),
    ]
