# Generated by Django 5.2.7 on 2025-11-19 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_provider', '0003_alter_smsmessage_table_alter_smsprovider_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='smsprovider',
            table='provider_type',
        ),
    ]
