# Generated by Django 5.2.7 on 2025-11-19 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_provider', '0004_alter_smsprovider_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='smsmessage',
            table='sms_provider_message',
        ),
        migrations.AlterModelTable(
            name='smsprovider',
            table='sms_provider_type',
        ),
    ]
